language: node_js

node_js:
  - "8.11.3"

install:
  - gem install html-proofer

script:
  - htmlproofer ./public

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  message: "Deployed by Travis Ci"

stages:
  - name: deploy
    if: branch = master
