language: node_js

node_js:
  - "8.11.3"

install:
  - gem install html-proofer

script:
  - htmlproofer ./public

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  message: "$TRAVIS_JOB_NUMBER: $TRAVIS_COMMIT_MESSAGE"

stages:
  - name: deploy
    if: branch = master
