language: node_js

node_js:
  - "8.11.3"

before_install:
  - ruby --version
  - rvm install 2.5.1
  - ruby --version

install:
  - npm install -g firebase-tools
  - gem install html-proofer

script:
  - htmlproofer ./public

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
